In [ ]:
s="hamza"


In [ ]:
s

In [ ]:
import cv from opencv2


In [ ]:
import cv2

In [ ]:
import numpy as np

In [ ]:
img = cv2.imread('test.JPG',0)
img2 = img.copy()
template = cv2.imread('template.png',0)
w, h = template.shape[::-1]

In [ ]:
img


In [ ]:
methods = ['cv2.TM_CCOEFF', 'cv2.TM_CCOEFF_NORMED', 'cv2.TM_CCORR',
            'cv2.TM_CCORR_NORMED', 'cv2.TM_SQDIFF', 'cv2.TM_SQDIFF_NORMED']

for meth in methods:
    img = img2.copy()
    method = eval(meth)

    # Apply template Matching
    res = cv2.matchTemplate(img,template,method)
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)

    # If the method is TM_SQDIFF or TM_SQDIFF_NORMED, take minimum
    if method in [cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED]:
        top_left = min_loc
    else:
        top_left = max_loc
    bottom_right = (top_left[0] + w, top_left[1] + h)

    cv2.rectangle(img,top_left, bottom_right, 255, 2)

    plt.subplot(121),plt.imshow(res,cmap = 'gray')
    plt.title('Matching Result'), plt.xticks([]), plt.yticks([])
    plt.subplot(122),plt.imshow(img,cmap = 'gray')
    plt.title('Detected Point'), plt.xticks([]), plt.yticks([])
    plt.suptitle(meth)

    plt.show()

In [ ]:
from matplotlib import pyplot as plt



In [ ]:
clear

In [ ]:
from PIL import Image
import pytesseract

im = Image.open("test.JPG")

text = pytesseract.image_to_string(im, lang = 'eng')

print(text)

In [ ]:
from PIL import Image
import pytesseract

im = Image.open("sample1.jpg")

text = pytesseract.image_to_string(im, lang = 'eng')

print(text)

In [ ]:
from PIL import Image
import pytesseract

im = Image.open("test.JPG")

text = pytesseract.image_to_string(im, lang = 'eng')

print(text)

In [ ]:
print("asdf")

In [ ]:
Mat src = Imgcodecs.imread("test.JPG");
                Mat bt = new Mat();
                Imgproc.cvtColor(src, bt, Imgproc.COLOR_BGR2GRAY);
                Imgproc.threshold(bt, bt, 0, 255, Imgproc.THRESH_BINARY);
                Imgcodecs.imwrite("output.png",bt);

                int xmin = bt.cols();
                int ymin = bt.rows();
                int xmax=0;                
                int ymax=0;

                double[] pixel = new double[0];
                for (int x = 0; x < bt.cols(); x++) {
                    for (int y = 0; y < bt.rows(); y++) {

                        pixel = bt.get(y, x);

                        if( pixel[0] == 0)
                        {
                            if( x < xmin )
                            {
                                xmin = x;
                            }

                            if( y < ymin )
                            {
                                ymin = y;
                            }

                            if( x > xmax )
                            {
                                xmax = x;
                            }

                            if( y > ymax )
                            {
                                ymax = y;
                            }
                        }

                    }
                }
                //xmin = xmin - 3;  // you can try to uncomment these lines
                //ymin = ymin - 3;
                //xmax = xmax + 3;
                //ymax = ymax + 3;

                Rect roi = new Rect(xmin, ymin, xmax-xmin, ymax-ymin);
                Mat cr = new Mat(src, roi);

In [ ]:
import cv2
import numpy as np

In [ ]:
img = cv2.imread('test.JPG')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
_,thresh = cv2.threshold(gray,1,255,cv2.THRESH_BINARY)

In [ ]:
contours = cv2.findContours(thresh,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
cnt = contours[0]
x,y,w,h = cv2.boundingRect(cnt)

In [ ]:
crop = img[y:y+h,x:x+w]
cv2.imwrite('output.png',crop)

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
img = cv2.imread('test.JPG', 0)
img = cv2.medianBlur(img, 5)
thresh =     cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\
cv2.THRESH_BINARY,11,2)
plt.imshow(thresh)

image, contours, hierarchy =   cv2.findContours(thresh.copy(),cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)

cv2.drawContours(image, contours, -1, (0,255,0), 3)
plt.imshow(img)
plt.show()

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
img = cv2.imread('test.JPG', 0)
plt.imshow(img)
plt.show()

# to detect the boundary of the image

In [4]:
import cv2


def threshold(im, method):
    # make it grayscale
    im_gray = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)

    if method == 'fixed':
        threshed_im = cv2.threshold(im_gray, 128, 255, cv2.THRESH_BINARY)

    elif method == 'mean':
        threshed_im = cv2.adaptiveThreshold(im_gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 5, 7)

    elif method == 'gaussian':
        threshed_im = cv2.adaptiveThreshold(im_gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 5, 12)

    else:
        return None

    return threshed_im


image = cv2.imread('screen.jpg')

# threshold it
thresh = threshold(image, 'mean')
height,width,channels = image.shape
image_area = width*height
largest_area=0;
largest_contour_index=0
bounding_rect=0
print(image_area)
# find contours
_, contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)
cnts=[]
for i in contours:
    cnt=i
    area = cv2.contourArea(cnt)
    if (area>largest_area and area < (image_area - 20000)):
        largest_area=area
        largest_contour_index=i
        bounding_rect=cnt
cv2.drawContours(image, [bounding_rect], -1, (0, 255, 0), 10)
cv2.imwrite('output.jpg', image)

7837335


True

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('test_page.JPG',0)
edges = cv2.Canny(img,200,300)
plt.subplot(121),plt.imshow(img,cmap = 'gray')
plt.title('Original Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(edges,cmap = 'gray')
plt.title('Edge Image'), plt.xticks([]), plt.yticks([])

plt.show()

# To remove noise and backgrounds from the images

In [4]:
import cv2

image = cv2.imread('Image.jpeg')
print(image)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
 
# check to see if we should apply thresholding to preprocess the
# image
gray = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]
 
gray = cv2.medianBlur(gray, 3)

cv2.imwrite("new.jpg", gray)

[[[ 77  95  96]
  [ 86 104 105]
  [ 91 106 108]
  ...
  [ 43  93 113]
  [ 44  91 113]
  [ 43  90 112]]

 [[ 78  96  97]
  [ 87 105 106]
  [ 92 107 109]
  ...
  [ 44  94 114]
  [ 45  92 114]
  [ 45  92 114]]

 [[ 79  97  98]
  [ 89 107 108]
  [ 94 109 111]
  ...
  [ 45  95 115]
  [ 47  94 116]
  [ 46  93 115]]

 ...

 [[ 92  99  94]
  [ 94 101  96]
  [ 95 102  97]
  ...
  [100 112 100]
  [ 99 111  99]
  [ 98 110  98]]

 [[ 90  97  92]
  [ 92  99  94]
  [ 93 100  95]
  ...
  [100 112 100]
  [ 99 111  99]
  [ 98 110  98]]

 [[ 89  96  91]
  [ 90  97  92]
  [ 92  99  94]
  ...
  [100 112 100]
  [ 99 111  99]
  [ 98 110  98]]]


True

# crop the boundary, screen name and actions

In [38]:
import numpy as np
import cv2


def threshold(im, method):
    # make it grayscale
    im_gray = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)

    if method == 'fixed':
        threshed_im = cv2.threshold(im_gray, 128, 255, cv2.THRESH_BINARY)

    elif method == 'mean':
        threshed_im = cv2.adaptiveThreshold(im_gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 5, 7)

    elif method == 'gaussian':
        threshed_im = cv2.adaptiveThreshold(im_gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 5, 12)

    else:
        return None

    return threshed_im


image = cv2.imread('gray2.jpg')

# threshold it
thresh = threshold(image, 'mean')
height,width,channels = image.shape
image_area = width*height
largest_area=0;
largest_contour_index=0
bounding_rect=0
print(image_area)
# find contours
_, contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)
cnts=[]
for i in contours:
    cnt=i
    area = cv2.contourArea(cnt)
    if (area>largest_area and area < (image_area - 20000)):
        largest_area=area
        largest_contour_index=i
        bounding_rect=cnt


# img = image
# mask = np.ones_like(img) # Create mask where white is what we want, black otherwise
# cv2.drawContours(mask, [bounding_rect], -1, 255, -1) # Draw filled contour in mask
# out = np.ones_like(img) # Extract out the object and place into output image
# out[mask == 255] = img[mask == 255]

# # Now crop
# (x, y, z) = np.where(mask == 255)
# (topx, topy) = (np.min(x), np.min(y))
# (bottomx, bottomy) = (np.max(x), np.max(y))
# out = out[topx:bottomx+1, topy:bottomy+1]
x,y,w,h = cv2.boundingRect(bounding_rect)

screenName = image[0:y,0:width]
actions = image[y+h:height, 0:width]
out = image[y:y+h,x:x+w]

# Show the output image
cv2.imwrite('output.jpg', out)
cv2.imwrite('actions.jpg', actions)
cv2.imwrite('screen_name.jpg', screenName)

12192768


True

# to detect the inner boxes

In [28]:
import cv2


def threshold(im, method):
    # make it grayscale
    im_gray = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)

    if method == 'fixed':
        threshed_im = cv2.threshold(im_gray, 128, 255, cv2.THRESH_BINARY)

    elif method == 'mean':
        threshed_im = cv2.adaptiveThreshold(im_gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 5, 7)

    elif method == 'gaussian':
        threshed_im = cv2.adaptiveThreshold(im_gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 5, 12)

    else:
        return None

    return threshed_im


image = cv2.imread('screen.jpg')

# threshold it
thresh = threshold(image, 'mean')
height,width,channels = image.shape
image_area = width*height
largest_area=image_area;
largest_contour_index=0
bounding_rect=0
print(image_area)
# find contours
_, contours, hierarchy = cv2.findContours(thresh.copy(), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)
cnts=[]
for i in contours:
    cnt=i
    area = cv2.contourArea(cnt)
    (x,y,w,h) = cv2.boundingRect(cnt)
    if ((w > 1000 and w < 2000) and (h > 50 and h < 1000)):
        print(w,h)
        cnts.append(cnt)
    
cv2.drawContours(image, cnts, -1, (0, 255, 0), 10)
cv2.imwrite('output.jpg', image)

7837335
(1166, 397)
(1232, 463)
(1172, 403)
(1222, 226)
(1301, 303)
(1228, 232)
(1367, 243)
(1441, 321)
(1373, 249)
(1238, 469)
(1309, 310)
(1448, 328)


True

 # OCR with AWS Rekognition


In [2]:
import boto3
import cv2
import simplejson as json

img = cv2.imread('ocr_test_gray.jpg')

jpg_as_text = cv2.imencode('.jpg', img)[1].tostring()
session = boto3.Session(profile_name='phototype')
client = session.client('rekognition', region_name='ap-southeast-2')
response = client.detect_text(Image={
    'Bytes': jpg_as_text
})
print(response['TextDetections'][0]['DetectedText'])

B OK


In [3]:
response

{'ResponseMetadata': {'HTTPHeaders': {'connection': 'keep-alive',
   'content-length': '3445',
   'content-type': 'application/x-amz-json-1.1',
   'date': 'Tue, 01 May 2018 15:54:09 GMT',
   'x-amzn-requestid': 'dde11835-4d57-11e8-a349-453e9c57cd02'},
  'HTTPStatusCode': 200,
  'RequestId': 'dde11835-4d57-11e8-a349-453e9c57cd02',
  'RetryAttempts': 0},
 u'TextDetections': [{u'Confidence': 90.95767211914062,
   u'DetectedText': u'B OK',
   u'Geometry': {u'BoundingBox': {u'Height': 0.13369081914424896,
     u'Left': 0.11943987011909485,
     u'Top': 0.036412328481674194,
     u'Width': 0.5978915691375732},
    u'Polygon': [{u'X': 0.11943987011909485, u'Y': 0.036412328481674194},
     {u'X': 0.7173314094543457, u'Y': 0.035086389631032944},
     {u'X': 0.7178584933280945, u'Y': 0.1687772125005722},
     {u'X': 0.11996695399284363, u'Y': 0.17010314762592316}]},
   u'Id': 0,
   u'Type': u'LINE'},
  {u'Confidence': 88.51775360107422,
   u'DetectedText': u'C:D',
   u'Geometry': {u'BoundingBox'

In [15]:
detectedActions = [];
for text in response['TextDetections']:
    if (text['Type'] == 'LINE' and text['Confidence'] > 80):
        detectedActions.append(text['DetectedText'])
print(detectedActions)

here
here
here
[u'B OK', u'C:D', u'LOGIN: D']


In [13]:
s='Line'
if (s == 'Line' and s[0] == 'L'):
    print('got it')

got it
